// Everything the hub pages say, in English, French and Arabic (R-TABLE-9). French and Arabic are
// first drafts for Seif to review (TODO.md). Game names and Tunisian game words stay as they are.

import { plural, texts, type Lang } from "@platform/ui";

export const T = texts({
  en: {
    brandAria: "Dineri, all games",
    allGames: "All games",
    signIn: "Sign in",
    yourAccount: "Your account",
    language: "Language",
    home: {
      eyebrow: "Tunisian card and table games",
      title: "Deal in your friends.",
      lede: "Send them a link and play at the same table, on a phone or a PC. Nobody around? Play against bots.",
      gamesAria: "Games",
      comingLabel: "Coming to the table",
      soon: "Coming soon",
      soonAria: (name: string) => `${name}, coming soon`,
      bots: "bots from easy to hard",
      play: (name: string) => `Play ${name}`,
      closed: "Back in a moment",
    },
    entry: {
      invited: "You've been invited",
      joinTitle: "Join the table",
      joinLede: "Pick a name and take your seat. The game starts when every seat is taken.",
      noInvite: "This link has no invite code. Ask the table owner for the full link.",
      name: "Your name",
      namePlaceholder: "e.g. lam3i",
      takeSeat: "Take a seat",
      create: "Create a table",
      createHint: "You get a link to send to your friends.",
      orBots: "or play against bots",
      connecting: "Connecting to the server…",
      signedInAs: (name: string) => `Signed in as ${name}`,
    },
    lobby: {
      table: (game: string) => `${game} table`,
      full: "Everyone's here",
      waiting: (n: number) => `Waiting for ${n} more`,
      startsWhen: (n: number) => `The game starts as soon as all ${n} seats are taken.`,
      invite: "Invite your friends",
      inviteHint: "Send them this link. Anyone with it can take a free seat.",
      botsAt: "Bots you add play at",
      botLevel: "Bot level",
      seat: (n: number) => `Seat ${n}`,
      empty: "Empty",
      you: "you",
      owner: "owner",
      bot: "bot",
      away: "away",
      addBot: "Add a bot",
      makeOwner: "Make owner",
      remove: "Remove",
      start: "Start the game",
      waitOwner: "Waiting for the table owner to fill the seats.",
    },
    notices: {
      kicked: "The table owner removed you from the table.",
      left: "You left the table.",
      roomClosed: "That table was closed.",
      lost: "That table doesn't exist any more. Create a new one below, or ask for a new link.",
    },
    app: {
      elsewhere: "Open elsewhere",
      elsewhereLede: "Your seat is open in another tab or window, so this one has stepped back.",
      playHere: "Play here instead",
      takingBack: "Taking you back to your seat…",
      settingUp: "Setting up the table…",
      unknownGame: "This table plays a game this page doesn't know. Reload the page.",
    },
    signin: {
      title: "Sign in to Dineri",
      why: "An account keeps your name and language on every device. It's optional: guests play everything.",
      google: "Continue with Google",
      or: "or",
      email: "Email address",
      emailPlaceholder: "you@example.com",
      sendLink: "Email me a sign-in link",
      sent: (email: string) => `We sent a sign-in link to ${email}. Open it on this device to finish.`,
      spam: "Nothing after a minute? Look in your spam folder.",
      close: "Close",
      finishing: "Signing you in…",
      confirmEmail: "Which email address did you ask for the link with?",
      finish: "Sign in",
      done: "You're signed in.",
      toHub: "Go to the games",
      terms: "By signing in you accept the terms and the privacy policy.",
    },
    account: {
      title: "Your account",
      signedInWith: (how: string) => `Signed in with ${how}`,
      google: "Google",
      emailLink: "an email link",
      name: "Name at the table",
      nameHint: "Used when you create or join a table. You can still change it for one table.",
      language: "Language",
      save: "Save",
      saved: "Saved",
      signOut: "Sign out",
      deleteTitle: "Delete your account",
      deleteWhat: "This removes your profile and your sign-in for good. Tables you're at carry on without it.",
      deleteAsk: "Delete everything? This can't be undone.",
      deleteYes: "Yes, delete my account",
      cancel: "Cancel",
      deleted: "Your account was deleted.",
      signedOut: "You're not signed in.",
    },
    errors: {
      "invalid-email": "That email address doesn't look right.",
      network: "No connection. Check your internet and try again.",
      "too-many": "Too many tries. Wait a few minutes and try again.",
      "link-expired": "This sign-in link has expired or was already used. Ask for a new one.",
      "not-available": "Sign-in isn't available right now. You can keep playing as a guest.",
      "popup-blocked": "Your browser blocked the sign-in window. Allow pop-ups for this site and try again.",
      "account-exists": "This email already has an account with another sign-in method. Use that one.",
      "bad-name": "Pick a name (1 to 20 characters).",
      "signed-out": "Please sign in again.",
      generic: "Something went wrong. Try again in a moment.",
    },
    footer: {
      about: "About",
      privacy: "Privacy",
      terms: "Terms",
      note: "Free to play. No betting, no real money, ever.",
    },
    notFound: {
      title: "No table here",
      lede: "This page doesn't exist. Maybe the link was cut short.",
      back: "Back to the games",
    },
    draft: "Draft: to be reviewed before Dineri opens to everyone.",
  },
  fr: {
    brandAria: "Dineri, tous les jeux",
    allGames: "Tous les jeux",
    signIn: "Se connecter",
    yourAccount: "Votre compte",
    language: "Langue",
    home: {
      eyebrow: "Jeux de cartes et de société tunisiens",
      title: "Invitez vos amis à la table.",
      lede: "Envoyez-leur un lien et jouez à la même table, sur téléphone ou sur PC. Personne ? Jouez contre des bots.",
      gamesAria: "Jeux",
      comingLabel: "Bientôt sur la table",
      soon: "Bientôt",
      soonAria: (name: string) => `${name}, bientôt disponible`,
      bots: "bots de facile à difficile",
      play: (name: string) => `Jouer au ${name}`,
      closed: "De retour dans un instant",
    },
    entry: {
      invited: "Vous êtes invité",
      joinTitle: "Rejoindre la table",
      joinLede: "Choisissez un nom et prenez place. La partie commence quand toutes les places sont prises.",
      noInvite: "Ce lien n'a pas de code d'invitation. Demandez le lien complet à l'hôte de la table.",
      name: "Votre nom",
      namePlaceholder: "ex. lam3i",
      takeSeat: "Prendre place",
      create: "Créer une table",
      createHint: "Vous recevez un lien à envoyer à vos amis.",
      orBots: "ou jouez contre des bots",
      connecting: "Connexion au serveur…",
      signedInAs: (name: string) => `Connecté en tant que ${name}`,
    },
    lobby: {
      table: (game: string) => `Table de ${game}`,
      full: "Tout le monde est là",
      waiting: (n: number) => (n === 1 ? "Encore 1 joueur attendu" : `Encore ${n} joueurs attendus`),
      startsWhen: (n: number) => `La partie commence dès que les ${n} places sont prises.`,
      invite: "Invitez vos amis",
      inviteHint: "Envoyez-leur ce lien. Toute personne qui l'a peut prendre une place libre.",
      botsAt: "Niveau des bots ajoutés",
      botLevel: "Niveau des bots",
      seat: (n: number) => `Place ${n}`,
      empty: "Libre",
      you: "vous",
      owner: "hôte",
      bot: "bot",
      away: "absent",
      addBot: "Ajouter un bot",
      makeOwner: "Nommer hôte",
      remove: "Retirer",
      start: "Lancer la partie",
      waitOwner: "L'hôte de la table remplit les places.",
    },
    notices: {
      kicked: "L'hôte vous a retiré de la table.",
      left: "Vous avez quitté la table.",
      roomClosed: "Cette table a été fermée.",
      lost: "Cette table n'existe plus. Créez-en une ci-dessous, ou demandez un nouveau lien.",
    },
    app: {
      elsewhere: "Ouvert ailleurs",
      elsewhereLede: "Votre place est ouverte dans un autre onglet ou une autre fenêtre ; celle-ci s'est mise en retrait.",
      playHere: "Jouer ici plutôt",
      takingBack: "Retour à votre place…",
      settingUp: "Installation de la table…",
      unknownGame: "Cette table joue à un jeu que cette page ne connaît pas. Rechargez la page.",
    },
    signin: {
      title: "Se connecter à Dineri",
      why: "Un compte garde votre nom et votre langue sur tous vos appareils. C'est facultatif : les invités jouent à tout.",
      google: "Continuer avec Google",
      or: "ou",
      email: "Adresse e-mail",
      emailPlaceholder: "vous@exemple.com",
      sendLink: "Recevoir un lien de connexion",
      sent: (email: string) => `Nous avons envoyé un lien de connexion à ${email}. Ouvrez-le sur cet appareil pour terminer.`,
      spam: "Rien au bout d'une minute ? Regardez dans vos spams.",
      close: "Fermer",
      finishing: "Connexion en cours…",
      confirmEmail: "Avec quelle adresse e-mail avez-vous demandé le lien ?",
      finish: "Se connecter",
      done: "Vous êtes connecté.",
      toHub: "Aller aux jeux",
      terms: "En vous connectant, vous acceptez les conditions et la politique de confidentialité.",
    },
    account: {
      title: "Votre compte",
      signedInWith: (how: string) => `Connecté avec ${how}`,
      google: "Google",
      emailLink: "un lien par e-mail",
      name: "Nom à la table",
      nameHint: "Utilisé quand vous créez ou rejoignez une table. Vous pouvez toujours le changer pour une table.",
      language: "Langue",
      save: "Enregistrer",
      saved: "Enregistré",
      signOut: "Se déconnecter",
      deleteTitle: "Supprimer votre compte",
      deleteWhat: "Cela supprime définitivement votre profil et votre connexion. Les tables où vous êtes continuent sans lui.",
      deleteAsk: "Tout supprimer ? C'est irréversible.",
      deleteYes: "Oui, supprimer mon compte",
      cancel: "Annuler",
      deleted: "Votre compte a été supprimé.",
      signedOut: "Vous n'êtes pas connecté.",
    },
    errors: {
      "invalid-email": "Cette adresse e-mail ne semble pas correcte.",
      network: "Pas de connexion. Vérifiez votre internet et réessayez.",
      "too-many": "Trop d'essais. Attendez quelques minutes et réessayez.",
      "link-expired": "Ce lien de connexion a expiré ou a déjà servi. Demandez-en un nouveau.",
      "not-available": "La connexion n'est pas disponible pour le moment. Vous pouvez continuer à jouer en invité.",
      "popup-blocked": "Votre navigateur a bloqué la fenêtre de connexion. Autorisez les pop-ups pour ce site et réessayez.",
      "account-exists": "Cette adresse a déjà un compte avec une autre méthode de connexion. Utilisez celle-ci.",
      "bad-name": "Choisissez un nom (1 à 20 caractères).",
      "signed-out": "Veuillez vous reconnecter.",
      generic: "Un problème est survenu. Réessayez dans un instant.",
    },
    footer: {
      about: "À propos",
      privacy: "Confidentialité",
      terms: "Conditions",
      note: "Gratuit. Aucun pari, aucun argent réel, jamais.",
    },
    notFound: {
      title: "Pas de table ici",
      lede: "Cette page n'existe pas. Le lien a peut-être été coupé.",
      back: "Retour aux jeux",
    },
    draft: "Brouillon : à relire avant l'ouverture de Dineri à tous.",
  },
  ar: {
    brandAria: "Dineri، كل الألعاب",
    allGames: "كل الألعاب",
    signIn: "تسجيل الدخول",
    yourAccount: "حسابك",
    language: "اللغة",
    home: {
      eyebrow: "ألعاب الورق والطاولة التونسية",
      title: "ادعُ أصدقاءك إلى الطاولة.",
      lede: "أرسل لهم رابطًا والعبوا على الطاولة نفسها، من الهاتف أو الحاسوب. لا أحد متاح؟ العب ضد الروبوتات.",
      gamesAria: "الألعاب",
      comingLabel: "قريبًا على الطاولة",
      soon: "قريبًا",
      soonAria: (name: string) => `${name}، قريبًا`,
      bots: "روبوتات من السهل إلى الصعب",
      play: (name: string) => `العب ${name}`,
      closed: "نعود بعد قليل",
    },
    entry: {
      invited: "لقد تمت دعوتك",
      joinTitle: "انضم إلى الطاولة",
      joinLede: "اختر اسمًا واجلس. تبدأ اللعبة عندما تمتلئ كل المقاعد.",
      noInvite: "هذا الرابط بلا رمز دعوة. اطلب الرابط الكامل من صاحب الطاولة.",
      name: "اسمك",
      namePlaceholder: "مثلًا lam3i",
      takeSeat: "اجلس",
      create: "أنشئ طاولة",
      createHint: "ستحصل على رابط ترسله لأصدقائك.",
      orBots: "أو العب ضد الروبوتات",
      connecting: "جارٍ الاتصال بالخادم…",
      signedInAs: (name: string) => `مسجّل الدخول باسم ${name}`,
    },
    lobby: {
      table: (game: string) => `طاولة ${game}`,
      full: "الجميع هنا",
      waiting: (n: number) => plural("ar", n, { one: "في انتظار لاعب واحد", two: "في انتظار لاعبَين", few: "في انتظار # لاعبين", other: "في انتظار # لاعبًا" }),
      startsWhen: (n: number) => `تبدأ اللعبة حين تمتلئ المقاعد الـ${n}.`,
      invite: "ادعُ أصدقاءك",
      inviteHint: "أرسل لهم هذا الرابط. كل من يملكه يستطيع أن يجلس في مقعد شاغر.",
      botsAt: "مستوى الروبوتات المضافة",
      botLevel: "مستوى الروبوت",
      seat: (n: number) => `المقعد ${n}`,
      empty: "شاغر",
      you: "أنت",
      owner: "صاحب الطاولة",
      bot: "روبوت",
      away: "غائب",
      addBot: "أضف روبوتًا",
      makeOwner: "اجعله صاحب الطاولة",
      remove: "أزِل",
      start: "ابدأ اللعبة",
      waitOwner: "في انتظار أن يملأ صاحب الطاولة المقاعد.",
    },
    notices: {
      kicked: "أزالك صاحب الطاولة منها.",
      left: "غادرت الطاولة.",
      roomClosed: "أُغلقت تلك الطاولة.",
      lost: "تلك الطاولة لم تعد موجودة. أنشئ طاولة جديدة أدناه، أو اطلب رابطًا جديدًا.",
    },
    app: {
      elsewhere: "مفتوح في مكان آخر",
      elsewhereLede: "مقعدك مفتوح في علامة تبويب أو نافذة أخرى، لذلك توقفت هذه.",
      playHere: "العب هنا بدلًا من ذلك",
      takingBack: "نعيدك إلى مقعدك…",
      settingUp: "نجهّز الطاولة…",
      unknownGame: "هذه الطاولة تلعب لعبة لا تعرفها هذه الصفحة. أعد تحميل الصفحة.",
    },
    signin: {
      title: "سجّل الدخول إلى Dineri",
      why: "يحفظ الحساب اسمك ولغتك على كل أجهزتك. وهو اختياري: الضيوف يلعبون كل شيء.",
      google: "المتابعة باستخدام Google",
      or: "أو",
      email: "البريد الإلكتروني",
      emailPlaceholder: "you@example.com",
      sendLink: "أرسل لي رابط الدخول",
      sent: (email: string) => `أرسلنا رابط الدخول إلى ${email}. افتحه على هذا الجهاز لإتمام الدخول.`,
      spam: "لم يصل شيء بعد دقيقة؟ تفقّد مجلد الرسائل غير المرغوب فيها.",
      close: "إغلاق",
      finishing: "جارٍ تسجيل دخولك…",
      confirmEmail: "ما البريد الإلكتروني الذي طلبت به الرابط؟",
      finish: "تسجيل الدخول",
      done: "لقد سجّلت الدخول.",
      toHub: "اذهب إلى الألعاب",
      terms: "بتسجيل الدخول فإنك تقبل الشروط وسياسة الخصوصية.",
    },
    account: {
      title: "حسابك",
      signedInWith: (how: string) => `تم الدخول عبر ${how}`,
      google: "Google",
      emailLink: "رابط بالبريد الإلكتروني",
      name: "اسمك على الطاولة",
      nameHint: "يُستعمل عندما تنشئ طاولة أو تنضم إليها. ويمكنك تغييره لطاولة واحدة.",
      language: "اللغة",
      save: "حفظ",
      saved: "تم الحفظ",
      signOut: "تسجيل الخروج",
      deleteTitle: "حذف حسابك",
      deleteWhat: "يحذف هذا ملفك الشخصي ودخولك نهائيًا. الطاولات التي تجلس عليها تستمر من دونه.",
      deleteAsk: "حذف كل شيء؟ لا يمكن التراجع عن ذلك.",
      deleteYes: "نعم، احذف حسابي",
      cancel: "إلغاء",
      deleted: "تم حذف حسابك.",
      signedOut: "أنت لم تسجّل الدخول.",
    },
    errors: {
      "invalid-email": "يبدو أن عنوان البريد الإلكتروني غير صحيح.",
      network: "لا يوجد اتصال. تحقّق من الإنترنت ثم حاول مجددًا.",
      "too-many": "محاولات كثيرة. انتظر بضع دقائق ثم حاول مجددًا.",
      "link-expired": "انتهت صلاحية رابط الدخول هذا أو استُعمل من قبل. اطلب رابطًا جديدًا.",
      "not-available": "تسجيل الدخول غير متاح الآن. يمكنك مواصلة اللعب كضيف.",
      "popup-blocked": "حظر متصفحك نافذة الدخول. اسمح بالنوافذ المنبثقة لهذا الموقع ثم حاول مجددًا.",
      "account-exists": "لهذا البريد حساب بطريقة دخول أخرى. استعمل تلك الطريقة.",
      "bad-name": "اختر اسمًا (من 1 إلى 20 حرفًا).",
      "signed-out": "يرجى تسجيل الدخول من جديد.",
      generic: "حدث خطأ ما. حاول بعد لحظة.",
    },
    footer: {
      about: "عن Dineri",
      privacy: "الخصوصية",
      terms: "الشروط",
      note: "مجاني. لا رهان ولا مال حقيقي، أبدًا.",
    },
    notFound: {
      title: "لا طاولة هنا",
      lede: "هذه الصفحة غير موجودة. ربما انقطع الرابط.",
      back: "العودة إلى الألعاب",
    },
    draft: "مسودة: تُراجع قبل فتح Dineri للجميع.",
  },
});

export type AccountErrorKey = keyof (typeof T)["en"]["errors"];
export type { Lang };
